
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class NewJFrame extends javax.swing.JFrame {

    private Statement Statement;
    Connection con2 = null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public int klj;
    SelectJFrame sjf;
    
    /**
     *
     */
    //public int klj;
    

    /**
     * Creates new form NewJFrame
     */
    
    
    public NewJFrame() {
        super("Users");
        //int klj = Integer.parseInt(jLabel2.getText());
        //this.klj=Integer.parseInt(jLabel2.getText());
        initComponents();
//        ds();
        show_user();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Identification-Badge-icon.png")));
        jButton6.setVisible(false);
        //klj=Integer.parseInt(jTextField1.getText());
        //klj=model.getValueAt(selectedRowIndex, 0).toString();
//        public int ui;
//        ui=Integer.parseInt(jTextField1.getText());
         ////jLabel2.setText(String.valueOf(ui));
    }
    
    public ArrayList<User> userList(){
        ArrayList<User> usersList=new ArrayList<>();
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String url = "jdbc:sqlserver://localhost:1433;databaseName=SSAR1;user=admin;password=admin;";
           //String url = "jdbc:derby://localhost:1533/ssar1";
           Connection con = DriverManager.getConnection(url);
           String query1="SELECT * FROM fio";
           Statement=con.createStatement();
           ResultSet rs= Statement.executeQuery(query1);
           User user;
           while(rs.next()){
               user=new User(rs.getInt("fio_id"), rs.getString("fio1"));
               usersList.add(user);
           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return usersList;
    }
    
    public void show_user(){
        ArrayList<User> list=userList();
        DefaultTableModel model=(DefaultTableModel)jTable_1.getModel();
        Object[] row=new Object[2];
        for (int i=0;i<list.size();i++){
            row[0]=list.get(i).getFIOid();
            row[1]=list.get(i).getFIO();
            model.addRow(row);
        }
    }
    
    public void showTableData(){
        DefaultTableModel model2 = (DefaultTableModel) jTable_1.getModel();
        
        while(model2.getRowCount()>0){
            for(int i=0; i<model2.getRowCount();i++){
                model2.removeRow(i);
            }
        }
        
//        String url2 = "jdbc:sqlserver://localhost:1433;databaseName=SSAR1;user=admin;password=admin;";
//        try {
//            con2=DriverManager.getConnection(url2);
//            String query2="select * from fio";
//        pst = con2.prepareStatement(query2);
//        rs=pst.executeQuery();
//        jTable_1.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }  
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIOid", "FIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_1);

        jButton1.setText("Click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Graphik");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Options");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("FRAME");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String jTextField;
        // TODO add your handling code here:
        String s = jTextField1.getText();
        int hj = Integer.parseInt(s)+1;
        System.out.println(hj);
        System.out.println(s);
        jLabel1.setText(Integer.toString(hj));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                try{
            String url1 = "insert into fio (fio1) values (?)";
            
                       String url = "jdbc:sqlserver://localhost:1433;databaseName=SSAR1;user=admin;password=admin;";
           //String url = "jdbc:derby://localhost:1533/ssar1";
           con2 = DriverManager.getConnection(url);
           pst = con2.prepareStatement(url1);
           pst.setString(1, jTextField2.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "inserted successfully");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        showTableData();
        show_user();

                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // UPDATE TODO add your handling code here:
                        try{
            String url1 = "UPDATE fio SET fio1=? WHERE fio_id=?";
            
                       String url = "jdbc:sqlserver://localhost:1433;databaseName=SSAR1;user=admin;password=admin;";
           //String url = "jdbc:derby://localhost:1533/ssar1";
           con2 = DriverManager.getConnection(url);
           pst = con2.prepareStatement(url1);
           pst.setString(1, jTextField2.getText());
           pst.setString(2, jTextField1.getText());
           //pst.setString(3, jTextField2.getText());
           //pst.setString(2, jTextField2.getString("fio1"));
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "updated successfully");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        showTableData();
        show_user();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // DELETE TODO add your handling code here:
                                try{
            String url1 = "DELETE FROM fio WHERE fio1=? and fio_id=?";
            
                       String url = "jdbc:sqlserver://localhost:1433;databaseName=SSAR1;user=admin;password=admin;";
           //String url = "jdbc:derby://localhost:1533/ssar1";
           con2 = DriverManager.getConnection(url);
           pst = con2.prepareStatement(url1);
           pst.setString(1, jTextField2.getText());
           pst.setString(2, jTextField1.getText());
           //pst.setString(2, jTextField2.getString("fio1"));
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "deleted successfully");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
                                
        showTableData();
        show_user();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTable_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel) jTable_1.getModel();
        int selectedRowIndex = jTable_1.getSelectedRow();
        
        jTextField1.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField2.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jLabel2.setText(model.getValueAt(selectedRowIndex, 0).toString());
        try{
            jButton6.setVisible(true);
            klj=Integer.parseInt(jLabel2.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jTable_1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new MainJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //new SelectJFrame().setVisible(true);
        new User3().kjh=Integer.parseInt(jTextField1.getText());
        new User3().fio=jTextField2.getText();
        sjf=new SelectJFrame();
        sjf.setVisible(true);
        //user3.setVisible(true);
        
//////////        SelectJFrame LangID = new SelectJFrame();
////////////        LangID.setVisible(true);
//////////        String mn=jTextField1.getText();
//////////        //LangID.setVisible(true);
//////////        int ijn = Integer.parseInt(mn);
//////////        System.out.println(ijn+"m");
//////////        LangID.ij=ijn;
//////////        LangID.ij2=2;
//////////        LangID.setVisible(true);
        //ui=ijn;
        //System.out.println(ui+"s");
//        new SelectJFrame().ij=ijn;
//        new SelectJFrame().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
//////////        public void ds(){
//////////            SelectJFrame LangID = new SelectJFrame();
//////////            String mn=jTextField1.getText();
//////////            int ijn = Integer.parseInt(mn);
//////////            System.out.println(ijn+"m");
//////////            LangID.ij=Integer.parseInt(mn);
//////////            LangID.ij2=2;
//////////        }
    
//////////////////    public void getIJ(){
//////////////////        return ijn;
//////////////////    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
            
//            public void addData(ConnectionDB connect) {
//            ResultSet result = connect.resultSetQuery("SELECT * FROM FIO");
//        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables


}
